name: Automatización de Cupos UNAM

on:
  schedule:
    # Se ejecuta en los minutos :12 y :42 de cada hora
    - cron: '12,42 15-23,0-1 3-7 8 *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-extraccion]

permissions:
  contents: write

jobs:
  extraccion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Crear carpeta y ejecutar scripts
        run: |
          mkdir -p Documentación
          python scraping/extractorHor_HTML.py
          mv datos_crudos.html Documentación/datos_crudos.html
          python scraping/generador_csv.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Documentación/
          git status
          git commit -m "Actualización de cupos: $(date)" || echo "No hubo cambios para hacer commit"
          git push
